base_config: configs/tts/priorgrad.yaml
data_dir: "/u01/stt/tts/small-f2s/FastSpeech2/preprocessed_data/son"
raw_data_dir: "/u01/stt/tts/small-f2s/2022_norm/2022/norm/"

use_phone_stat: true
use_std_norm: false
std_min: 0.1
std_max: -1
use_std_only: false
use_mean_only: false
condition_phone_stat: false